---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(plotly)
library(ggridges)
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r}
library(p8105.datasets)
data("instacart")
```

```{r}
instacart_df = count(instacart, aisle) %>% 
  mutate(aisle = factor(aisle)) %>% 
  mutate(aisle_ranking = min_rank(desc(n)))  
instacart_df 

nrow(instacart_df)                          
arrange(instacart_df, aisle_ranking)
            
view(instacart_df)
```

### Bar chart: Number of orders from each aisle

```{r}
instacart_df %>% 
  mutate(aisle = reorder(aisle, n)) %>%      
  filter(n > 10000) %>%                      
  plot_ly(x = ~aisle, y = ~n, type = "bar", color = ~aisle, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Scatter plot: Number of orders of from each department for each day of week

```{r}
instacart %>% 
  count(order_dow, department) %>%
  rename(order_number = n, day_of_week = order_dow) %>%
  mutate(day_of_week = as.factor(day_of_week)) %>% 
  plot_ly(x = ~day_of_week, y = ~order_number, color = ~department, type = "scatter", mode = "line")
```

## Boxplot: Order hours for each day for each department

```{r}
instacart %>% 
  select(order_number,order_hour_of_day, department) %>%
  mutate(department = as.factor(department)) %>%
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box")
```